import type { Metadata } from "next";
import "./globals.css";
import { DataProvider } from "./_components/Store/DataProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang ="en">
      <body className="bg-black text-white">
        <DataProvider>
          {children}
        </DataProvider>
      </body>
    </html>
  );
}
